"""Migration 0029 adds the action ledger (ADR-0117).

Two tables, shaped after `approvals` and `approval_audit_entries`, because the
routing, lifecycle and audit needs are the ones those tables already answer.

Hand-written rather than autogenerated, and that is not a style preference.
Autogenerate compares against the wrong search path here and proposes dropping
Langfuse's `monitors`, `table_view_presets` and `default_llm_models`, which share
this database -- a generated revision would take three tables belonging to
another product with it.

What this test holds, beyond "the tables appear":

1. **The round trip.** upgrade, downgrade, upgrade. A downgrade that leaves a
   type, an index or a constraint behind passes a shape check on the way down and
   fails on the way back up, which is the state an operator rolling back an
   incident discovers at the worst moment.

2. **`dedupe_key` is unique in the database, not just in the writer.** The
   worker redelivers at least once (ADR-0013), so the second delivery of one turn
   must adopt the existing row rather than mint a second record of one call. A
   writer-side check is a race; the constraint is not.

3. **The audit trail dies with its action, not before it.** `ON DELETE CASCADE`,
   so a deleted action cannot leave orphaned rows claiming to audit something
   that is not there.

Follows `test_migration_0021_agent_channels.py`: a throwaway database all to
itself via `isolated_migration_db`, real Postgres, no mocking.
"""

from __future__ import annotations

import uuid

import pytest
from _migration_support import IsolatedMigrationDb, alembic_config, column_names, sql_rows
from alembic import command
from sqlalchemy.exc import IntegrityError

# The revision immediately below 0029, targeted explicitly rather than as "-1":
# a later migration moving head would make "-1" stop short of undoing 0029 and
# this file would go green while proving nothing (#1391).
BELOW = "0028"

# The revision immediately below 0032, which adds ``post_state``.
BELOW_0032 = "0031"

# The revision immediately below 0033, which adds ``gate_approval_id``.
BELOW_0033 = "0032"


def _table_exists(table: str) -> bool:
    return bool(
        sql_rows(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = 'curie' AND table_name = :t",
            {"t": table},
        )
    )


def _insert_action(dedupe_key: str, call_id: str = "toolu_01") -> uuid.UUID:
    action_id = uuid.uuid4()
    sql_rows(
        "INSERT INTO curie.agent_actions "
        "(id, conversation_id, call_id, tool, dedupe_key, status) "
        "VALUES (:id, 'C1', :call_id, 'scale_deployment', :key, 'pending')",
        {"id": action_id, "call_id": call_id, "key": dedupe_key},
    )
    return action_id


def test_the_upgrade_creates_both_ledger_tables(isolated_migration_db: IsolatedMigrationDb) -> None:
    isolated_migration_db.at("head")

    assert _table_exists("agent_actions")
    assert _table_exists("action_audit_entries")
    columns = column_names("agent_actions")
    assert {"prior_state", "target", "arguments", "result", "status"} <= columns


def test_the_ledger_round_trips_upgrade_downgrade_upgrade(
    isolated_migration_db: IsolatedMigrationDb,
) -> None:
    cfg = alembic_config()
    isolated_migration_db.at("head")

    command.downgrade(cfg, BELOW)
    assert not _table_exists("agent_actions")
    assert not _table_exists("action_audit_entries")

    command.upgrade(cfg, "head")
    assert _table_exists("agent_actions")
    assert _table_exists("action_audit_entries")


def test_one_call_cannot_be_recorded_twice(isolated_migration_db: IsolatedMigrationDb) -> None:
    """At-least-once redelivery must adopt the row, not fork a second record."""

    isolated_migration_db.at("head")
    _insert_action("event-1:toolu_01")

    with pytest.raises(IntegrityError):
        _insert_action("event-1:toolu_01")


def test_audit_rows_die_with_the_action_they_audit(
    isolated_migration_db: IsolatedMigrationDb,
) -> None:
    isolated_migration_db.at("head")
    action_id = _insert_action("event-2:toolu_01")
    sql_rows(
        "INSERT INTO curie.action_audit_entries "
        "(id, action_id, action, actor, authorizer, authorized) "
        "VALUES (:id, :action_id, 'undo_refused', 'someone', 'route', false)",
        {"id": uuid.uuid4(), "action_id": action_id},
    )

    sql_rows("DELETE FROM curie.agent_actions WHERE id = :id", {"id": action_id})

    assert sql_rows("SELECT 1 FROM curie.action_audit_entries") == []


def test_0032_round_trips_the_post_state_column(isolated_migration_db: IsolatedMigrationDb) -> None:
    """A column-add has to undo cleanly too.

    A downgrade that leaves the column behind passes a shape check on the way
    down and fails the re-upgrade with "column already exists", which is the
    state an operator rolling back an incident discovers at the worst moment.
    """

    cfg = alembic_config()
    isolated_migration_db.at("head")
    assert "post_state" in column_names("agent_actions")

    command.downgrade(cfg, BELOW_0032)
    assert "post_state" not in column_names("agent_actions")

    command.upgrade(cfg, "head")
    assert "post_state" in column_names("agent_actions")


def test_0033_round_trips_the_gate_column(isolated_migration_db: IsolatedMigrationDb) -> None:
    """The gate column undoes cleanly too.

    Worth its own assertion rather than trusting the 0030 pattern: this column is
    a permission input, and a downgrade that leaves it behind fails the
    re-upgrade at exactly the moment an operator is rolling back.
    """

    cfg = alembic_config()
    isolated_migration_db.at("head")
    assert "gate_approval_id" in column_names("agent_actions")

    command.downgrade(cfg, BELOW_0033)
    assert "gate_approval_id" not in column_names("agent_actions")

    command.upgrade(cfg, "head")
    assert "gate_approval_id" in column_names("agent_actions")
