// GENERATED by scripts/gen-themes.mjs -- do not edit.
//
// Lives beside the contract because BOTH sides need it: the shell maps a theme's
// appearance onto the native window, and the renderer draws the picker from it.

export type ThemeId =
  | "dark"
  | "light"
  | "dark-plus"
  | "light-plus"
  | "dark-modern"
  | "light-modern"
  | "hc-dark"
  | "hc-light"
  | "abyss"
  | "kimbie-dark"
  | "monokai"
  | "monokai-dimmed"
  | "quiet-light"
  | "red"
  | "solarized-dark"
  | "solarized-light"
  | "tomorrow-night-blue";

export interface ThemeInfo {
  readonly id: ThemeId;
  /** Whether the shell should put the native window in light or dark. */
  readonly appearance: "light" | "dark";
  readonly label: string;
  /** content, raised, accent -- enough to recognise the theme in a picker. */
  readonly swatch: readonly [string, string, string];
}

export const THEMES: readonly ThemeInfo[] = [
  {
    "id": "dark",
    "label": "Curie Dark",
    "appearance": "dark",
    "swatch": [
      "#1f1f21",
      "#242426",
      "#3ecf8e"
    ]
  },
  {
    "id": "light",
    "label": "Curie Light",
    "appearance": "light",
    "swatch": [
      "#e4e6eb",
      "#eaecf1",
      "#0f8f62"
    ]
  },
  {
    "id": "dark-plus",
    "label": "Dark+",
    "appearance": "dark",
    "swatch": [
      "#333333",
      "#272727",
      "#007acc"
    ]
  },
  {
    "id": "light-plus",
    "label": "Light+",
    "appearance": "light",
    "swatch": [
      "#f3f3f3",
      "#f4f4f4",
      "#007acc"
    ]
  },
  {
    "id": "dark-modern",
    "label": "Dark Modern",
    "appearance": "dark",
    "swatch": [
      "#181818",
      "#282828",
      "#0078d4"
    ]
  },
  {
    "id": "light-modern",
    "label": "Light Modern",
    "appearance": "light",
    "swatch": [
      "#f8f8f8",
      "#f4f4f4",
      "#005fb8"
    ]
  },
  {
    "id": "hc-dark",
    "label": "Dark High Contrast",
    "appearance": "dark",
    "swatch": [
      "#0d0d0d",
      "#0d0d0d",
      "#f38518"
    ]
  },
  {
    "id": "hc-light",
    "label": "Light High Contrast",
    "appearance": "light",
    "swatch": [
      "#f0f0f0",
      "#f4f4f4",
      "#0f4a85"
    ]
  },
  {
    "id": "abyss",
    "label": "Abyss",
    "appearance": "dark",
    "swatch": [
      "#051221",
      "#051221",
      "#2277ff"
    ]
  },
  {
    "id": "kimbie-dark",
    "label": "Kimbie Dark",
    "appearance": "dark",
    "swatch": [
      "#2b2115",
      "#2b2115",
      "#a57a4c"
    ]
  },
  {
    "id": "monokai",
    "label": "Monokai",
    "appearance": "dark",
    "swatch": [
      "#31322c",
      "#31322c",
      "#a6e22e"
    ]
  },
  {
    "id": "monokai-dimmed",
    "label": "Monokai Dimmed",
    "appearance": "dark",
    "swatch": [
      "#353535",
      "#262726",
      "#6a9fb5"
    ]
  },
  {
    "id": "quiet-light",
    "label": "Quiet Light",
    "appearance": "light",
    "swatch": [
      "#e6e6e6",
      "#eaeaea",
      "#705697"
    ]
  },
  {
    "id": "red",
    "label": "Red",
    "appearance": "dark",
    "swatch": [
      "#430c0c",
      "#430c0c",
      "#e35353"
    ]
  },
  {
    "id": "solarized-dark",
    "label": "Solarized Dark",
    "appearance": "dark",
    "swatch": [
      "#07313b",
      "#07313b",
      "#268bd2"
    ]
  },
  {
    "id": "solarized-light",
    "label": "Solarized Light",
    "appearance": "light",
    "swatch": [
      "#eee7d5",
      "#f2ebd9",
      "#268bd2"
    ]
  },
  {
    "id": "tomorrow-night-blue",
    "label": "Tomorrow Night Blue",
    "appearance": "dark",
    "swatch": [
      "#0d2f5a",
      "#0d2f5a",
      "#bbdaff"
    ]
  }
] as const;

export const THEME_IDS: readonly ThemeId[] = THEMES.map((t) => t.id);

export function themeInfo(id: string): ThemeInfo | undefined {
  return THEMES.find((t) => t.id === id);
}
