"""The published verification contract's command gate (#1041).

`docs/agents.md` tells an agent which commands prove an outcome. Nothing
recomputed those names, so the contract could keep naming a command the CLI had
renamed or dropped, and the agent would trust it. This gate resolves every
`curie ...` invocation the contract names against the committed
`cli/command-manifest.json`, which `cli/tests/command_surface.rs` already pins
against the live clap grammar.

Four failure modes matter equally and all are asserted here: the manifest moved
out from under the contract (a leaf removed, a leaf renamed), the contract
drifted away from the manifest (a subcommand that never existed, an undeclared
flag, a placeholder), a required artifact went missing or stopped parsing, and
the contract stopped naming commands at all. The last is the vacuity guard: a
green gate over an unverified contract is the defect one level up from the one
this ticket reports.

Every test drives `main(["--repo-root", str(root)])` through the `run_lint`
fixture and asserts on exit code and output text only, per the frozen
convention in `conftest.py`. No test imports the check or touches a `Finding`,
so renaming a helper does not break this suite.

`fixtures/clean_repo/cli/command-manifest.json` is a HAND-AUTHORED test
artifact. It is deliberately NOT regenerated by `curie schema`: it is a
miniature written to carry one of each branch the resolver walks (a root-only
`global: true` flag, a root-only NON-global flag, a nested subcommand group, a
leaf with its own non-global arg, a hidden leaf). Regenerating it from the real
CLI would replace it with 3000 lines that no longer isolate those branches.

The two root flags exist as a pair on purpose: the global one proves scope is
INHERITED by every descendant, the non-global one proves that inheritance is
BOUNDED. Either alone is satisfied by a resolver that inherits everything.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .conftest import RunLint, write

_CONTRACT = "docs/agents.md"
_MANIFEST = "cli/command-manifest.json"


def _read_manifest(root: Path) -> dict[str, Any]:
    manifest: dict[str, Any] = json.loads((root / _MANIFEST).read_text(encoding="utf-8"))
    return manifest


def _write_manifest(root: Path, manifest: dict[str, Any]) -> None:
    write(root, _MANIFEST, json.dumps(manifest, indent=2, sort_keys=True) + "\n")


def _skill_leaves(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    """The `curie skill` group's own subcommand list, mutated in place by callers."""
    skill = next(node for node in manifest["subcommands"] if node["name"] == "skill")
    leaves: list[dict[str, Any]] = skill["subcommands"]
    return leaves


def _append(root: Path, text: str) -> None:
    """Append a line to the fixture contract, leaving its existing commands in place."""
    path = root / _CONTRACT
    path.write_text(path.read_text(encoding="utf-8") + text, encoding="utf-8")


# --- the baseline: without it every negative test could pass for the wrong
# --- reason ----------------------------------------------------------------


def test_valid_contract_passes(clean_repo: Path, run_lint: RunLint) -> None:
    # Positive control. The unmutated fixture contract names only commands the
    # fixture manifest carries, so the gate must be silent. A gate that reports
    # everything is no gate.
    code, out = run_lint(clean_repo)
    assert code == 0, out


# --- the manifest moved out from under the contract ------------------------


def test_removed_command_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # THE ticket's own defect, proven by mutating the MANIFEST rather than the
    # contract: a leaf the contract names is dropped from the CLI and the
    # contract still names it. Mutating the doc instead would leave this
    # direction (the one that actually happens, because CLI churn is what moves)
    # entirely unproven.
    manifest = _read_manifest(clean_repo)
    leaves = _skill_leaves(manifest)
    leaves[:] = [leaf for leaf in leaves if leaf["name"] != "status"]
    _write_manifest(clean_repo, manifest)
    code, out = run_lint(clean_repo)
    assert code != 0
    # Both halves are load-bearing: the offending command so the failure is
    # actionable, and the doc path so the reader knows which file to fix.
    assert "status" in out
    assert _CONTRACT in out


def test_renamed_command_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # Distinct from removal: a resolver that special-cased an absent node but
    # not a substituted one would pass the test above and fail here. The new
    # spelling deliberately does not contain the old one, so asserting on the
    # old spelling cannot pass by accident.
    manifest = _read_manifest(clean_repo)
    for leaf in _skill_leaves(manifest):
        if leaf["name"] == "status":
            leaf["name"] = "state"
    _write_manifest(clean_repo, manifest)
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "status" in out
    assert _CONTRACT in out


# --- the contract drifted away from the manifest ---------------------------


def test_global_json_flag_resolves_on_a_leaf(clean_repo: Path, run_lint: RunLint) -> None:
    # THE most important false-positive guard in this suite. `--json` is
    # declared exactly once, on the manifest ROOT, with `global: true`. A flag
    # checker that reads only the resolved leaf's own `args` fails every line of
    # the real contract, the gate looks broken, and the fix people reach for is
    # to weaken it. The contract here is reduced to that single line so nothing
    # else can be the reason it passes.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nAfter bringing the tier up: `curie skill status --json` exits 0.\n",
    )
    code, out = run_lint(clean_repo)
    assert code == 0, out


def test_short_flag_resolves_on_a_leaf(clean_repo: Path, run_lint: RunLint) -> None:
    # The short-flag half of `_lookup_flag`. `--quiet` is declared global on the
    # manifest root with `"short": "q"`, so `-q` must match on `short` the same
    # way `--json` matches on `long` above. A resolver that mutated the lookup
    # key to always read `"long"` would pass every long-flag test in this file
    # and only fail here.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nQuiet mode: `curie skill status -q` exits 0.\n",
    )
    code, out = run_lint(clean_repo)
    assert code == 0, out


def test_undeclared_short_flag_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # Partner to the test above, and neither may be deleted: alone, each is
    # satisfied by a degenerate matcher (accept every short flag, or reject
    # every short flag). Together they prove short-flag validation is real.
    _append(clean_repo, "\nSomething terse: `curie skill status -z`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "-z" in out


def test_non_global_root_flag_is_not_inherited_by_a_leaf(
    clean_repo: Path, run_lint: RunLint
) -> None:
    # Scope is inherited, and inheritance is BOUNDED. The fixture root declares
    # `--version` with `global: false`, so it is legal on the root and on
    # nothing else. Deletion check: widening the accumulation from "each
    # ancestor's global args" to "each ancestor's args" makes every root flag
    # legal everywhere and reds only this test -- the two tests above stay green,
    # because they only prove that globals ARE inherited and that unknown flags
    # are rejected, never that a known-but-local flag is confined.
    _append(clean_repo, "\nThe version is printed by `curie skill status --version`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "--version" in out


def test_leaf_local_flag_is_not_accepted_on_a_sibling(
    clean_repo: Path, run_lint: RunLint
) -> None:
    # The sideways direction of the same rule. `--cases` is declared non-global
    # on the sibling leaf `skill eval`, so it must not resolve on `skill status`.
    # A resolver that pooled every flag it had ever seen in the manifest -- the
    # obvious "just make the false positives stop" fix -- passes every other
    # test in this file and reds here.
    _append(clean_repo, "\nThe case file is named by `curie skill status --cases`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "--cases" in out


def test_invocation_naming_no_subcommand_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # The per-invocation vacuity guard, distinct from the file-level one below:
    # this one fires when a contract line names the binary and nothing else, so
    # there is no leaf to resolve and the line verifies nothing. Without it
    # `curie --json` stands in the contract as a checked command while being
    # unrunnable. Deletion check: turning the guard off reds this test and
    # nothing else, because every other negative case here reaches a real leaf.
    _append(clean_repo, "\nThe binary is `curie`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0

    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nStructured output everywhere: `curie --json`.\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0


def test_wrapped_invocation_is_not_skipped(clean_repo: Path, run_lint: RunLint) -> None:
    # A contract that shows an agent how to capture a value writes
    # `$(curie ... | jq -r .url)`, and a shell-flavoured line writes
    # `(curie ...)`. If the opening token has to equal `curie` exactly, both
    # forms open no invocation at all and the command inside is silently
    # unchecked -- the gate passes while naming a dead verb, which is the worst
    # outcome available in this file. The file-level vacuity guard does not
    # cover this: it only fires when the contract names ZERO commands, and one
    # wrapped bad command among many good ones is invisible to it.
    _append(
        clean_repo,
        "\nCapture it: `curie skill status --json` and `$(curie skill bogusverb)`.\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "bogusverb" in out

    # The bare-paren form, which the `$` strip alone would not reach.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nIn a subshell: `(curie skill bogusverb)` reports the tier.\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "bogusverb" in out


def test_bogus_subcommand_after_a_flag_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # A flag does not end the command path for clap: `curie skill --json
    # bogusverb` is rejected by the real CLI, because `skill` declares no
    # positional arguments and `bogusverb` is not one of its subcommands. A
    # resolver that flips into "everything after a flag is a flag value" mode
    # certifies it instead, and the contract then tells an agent to run a
    # command that fails at runtime. This is the same silent-pass class as the
    # wrapped-invocation case above, reached from the other side.
    _append(clean_repo, "\nList the sessions with `curie skill --json bogusverb`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "bogusverb" in out


def test_global_flag_before_the_subcommand_path_resolves(
    clean_repo: Path, run_lint: RunLint
) -> None:
    # Mandatory partner to the test above, and neither may be deleted. A global
    # flag may legally precede the subcommand path, so `curie --json skill
    # status` is valid clap syntax and must stay silent. Alone, the test above
    # is satisfied by a resolver that rejects every token after any flag; alone,
    # this one is satisfied by a resolver that accepts everything. Together they
    # force the real rule: keep walking the subcommand path across a flag, and
    # only stop treating tokens as path elements once a leaf is reached.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nGlobal flags may lead: `curie --json skill status` exits 0.\n",
    )
    code, out = run_lint(clean_repo)
    assert code == 0, out


def test_hidden_command_resolves(clean_repo: Path, run_lint: RunLint) -> None:
    # `hidden: true` means "not advertised in --help", never "does not exist".
    # The real contract names `curie schema` as the authority on what commands
    # exist, and `curie schema` is hidden. This pins the decision against the
    # natural "helpful" refactor of filtering hidden nodes out of the tree,
    # which would silently break exactly that line. The baseline contract does
    # not name a hidden command, so deleting this test removes the only
    # coverage of that branch.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nWhen a command is uncertain, `curie schema` is the authority.\n",
    )
    code, out = run_lint(clean_repo)
    assert code == 0, out


def test_placeholder_in_contract_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # Placeholders are banned outright. The tier set is closed at three, so
    # writing them out costs three lines, and an expansion table would be a
    # second source of truth that can itself drift -- the failure class this
    # gate exists to prevent.
    #
    # This case alone does NOT prove the ban: `<tier>` sits in a subcommand
    # position, so deleting the placeholder branch entirely leaves the generic
    # "not a subcommand of `curie`" finding, which satisfies both assertions.
    # `test_placeholder_outside_a_subcommand_position_fails` is what actually
    # pins the ban; keep both, because this one pins the message an editor is
    # most likely to hit.
    _append(clean_repo, "\nAt the tier you deployed to: `curie <tier> status --json`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "<tier>" in out


def test_placeholder_outside_a_subcommand_position_fails(
    clean_repo: Path, run_lint: RunLint
) -> None:
    # The placeholder ban, proven. Both positions here are ones the subcommand
    # check cannot reach -- a flag value, and a positional after a leaf, both of
    # which the resolver otherwise accepts unconditionally -- so the only branch
    # that can report them is the placeholder branch. Asserting the word
    # `placeholder` rather than merely the token is the second half of the
    # proof: a generic finding that happened to quote the token would not
    # satisfy it. Deletion check: turning the placeholder branch off reds this
    # test and nothing else in the file.
    _append(clean_repo, "\nGrade a specific file with `curie skill eval --cases <file>`.\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "<file>" in out
    assert "placeholder" in out

    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nReport one session: `curie skill status <thing>`.\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "<thing>" in out
    assert "placeholder" in out


def test_contract_with_no_commands_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # The vacuity guard. A reword that drops the backticks would otherwise leave
    # a green gate over a contract nothing checks, which is a worse state than
    # no gate: the badge says verified. Deletion check: without this test,
    # stripping the backticks from the real contract keeps the suite green.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\nProse about proving outcomes, naming no command at all.\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert _CONTRACT in out


# --- a required artifact went missing or stopped parsing -------------------


def test_missing_contract_file_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # The _ROOT_DOCS lesson, applied to a second required artifact: filtering an
    # absent file out with `.is_file()` is what let ARCHITECTURE.md be deleted
    # for zero findings and exit 0. The gate must verify what is missing, not
    # only what is written, or one `git rm` undoes it.
    (clean_repo / _CONTRACT).unlink()
    code, out = run_lint(clean_repo)
    assert code != 0
    assert _CONTRACT in out


def test_missing_manifest_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # The other half of the same rule. Without it the gate goes vacuously green
    # in any tree where the manifest was moved or renamed: no ground truth, no
    # findings, exit 0.
    (clean_repo / _MANIFEST).unlink()
    code, out = run_lint(clean_repo)
    assert code != 0
    assert _MANIFEST in out


def test_unparseable_manifest_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # A truncated manifest is a content problem, so it is a finding and a clean
    # non-zero exit, never a traceback: the linter reports, it does not crash.
    # An unhandled exception would surface here as a test ERROR rather than a
    # failed assertion, which is the distinction being pinned.
    write(clean_repo, _MANIFEST, '{"name": "curie", "subcomm')
    code, out = run_lint(clean_repo)
    assert code != 0
    assert _MANIFEST in out


def test_manifest_that_is_not_a_command_tree_fails(clean_repo: Path, run_lint: RunLint) -> None:
    # Valid JSON that is not a command tree. Distinct from the truncated case
    # above: that one never reaches the resolver, this one does, and every
    # accessor it walks (`.get("subcommands")`, `.get("args")`) is a `dict`
    # method a list does not have. The required outcome is the same as every
    # other bad-artifact case -- a finding naming the file and a clean non-zero
    # exit -- and specifically NOT an AttributeError, which would surface to a
    # contributor as a linter crash rather than as something to fix.
    write(clean_repo, _MANIFEST, "[]\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert _MANIFEST in out


# --- the scanning unit: what is scanned, and how much of it ----------------


def test_prose_mention_of_curie_is_not_scanned(clean_repo: Path, run_lint: RunLint) -> None:
    # Only code constructs are scanned. English is not a command line, and a
    # gate that fires on ordinary prose gets turned off. `publishes` is not a
    # subcommand, so a future "scan everything" change reds here instead of
    # reaching the real contract.
    _append(clean_repo, "\ncurie publishes this contract so an agent can trust it.\n")
    code, out = run_lint(clean_repo)
    assert code == 0, out


def test_second_invocation_in_one_unit_is_resolved(clean_repo: Path, run_lint: RunLint) -> None:
    # THE test standing between this suite and a first-occurrence-only resolver.
    # Every other negative test above puts its bad command in the first (or
    # only) invocation of its unit, so none of them exercises the resume step: a
    # resolver that validates one invocation per unit and swallows the rest as
    # flag values passes all of them.
    #
    # A scanning unit is ONE inline code span, or ONE line of a fenced block --
    # it is NOT a line of the rendered document. Two separately-backticked
    # commands sitting on the same source line are therefore two units holding
    # one invocation each, and the resume loop is never entered. Both
    # invocations must live inside a SINGLE span, or a single fenced line, for
    # this to test anything at all. Deletion check: `break` after the first
    # invocation of a unit reds this test and nothing else in the file.
    _append(
        clean_repo,
        "\nskill tier: `curie skill status --json && curie skill bogusverb`\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    # Asserting only non-zero is insufficient: the unit could fail for an
    # unrelated reason while the second invocation stayed unread.
    assert "bogusverb" in out

    # Partner, first position. Together the two prove the resolver reads BOTH
    # positions rather than happening to read one of them.
    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\n"
        "skill tier: `curie skill statuz --json && curie skill eval --json`\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "statuz" in out


def test_ignore_line_does_not_silence_a_command_finding(
    clean_repo: Path, run_lint: RunLint
) -> None:
    # The escape hatch is scoped to the citation walk and must never reach this
    # gate. An agent is told to trust the contract, so a suppressible command
    # check is worse than none: the hatch would let an editor silence a dead
    # command with one comment and leave CI green. The hatch is currently out of
    # reach only because the phase runs outside `_check_docs`, which is an
    # accident of placement rather than a stated rule -- a later refactor that
    # routes these findings through `_check_docs` "for consistency" would make
    # the gate suppressible, and this test is the only thing that would say so.
    # Both spellings are pinned because the hatch supports both.
    _append(clean_repo, "\n`curie skill bogusverb` <!-- doclint:ignore-line -->\n")
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "bogusverb" in out

    write(
        clean_repo,
        _CONTRACT,
        "# Fixture contract\n\n<!-- doclint:ignore-line -->\n`curie skill bogusverb`\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "bogusverb" in out


def test_second_invocation_on_a_fenced_line_is_resolved(
    clean_repo: Path, run_lint: RunLint
) -> None:
    # The other half of the unit definition. `_scanned_units` builds units from
    # two sources -- inline spans and fenced-block lines -- and the test above
    # only exercises the first. A regression that stopped emitting fenced lines
    # entirely would keep every inline-span test green while silently dropping
    # every command the contract writes in a copy-pasteable block, which is the
    # form an agent is most likely to run verbatim.
    _append(
        clean_repo,
        "\n```bash\ncurie skill status --json && curie skill bogusverb --json\n```\n",
    )
    code, out = run_lint(clean_repo)
    assert code != 0
    assert "bogusverb" in out
