"""agent_actions and action_audit_entries: what an agent did, and to what

The platform already knew a turn had mutated something. The runner classifies
every tool absent from a harness-declared read-only allowlist as side-effecting,
and the kernel reduced that to a boolean whose only consumer was the
no-retry-after-side-effects rule. These two tables are the record that boolean
could not be: which tool was called, with what arguments, against what target,
what state it read on the way past, and whether that is enough to put it back.

Shaped after ``approvals`` and ``approval_audit_entries`` on purpose. The
requirements are the same -- a row tied to a conversation, carrying the reply
handle of the surface that must be told, a status a human drives, and an audit
trail -- and the only difference is when the row is written. An approval is a
question asked before an action; this is the account of one after.

Written by hand rather than autogenerated. Autogenerate compared against the
wrong search path in the dev database: it proposed creating every table that
already exists and dropping Langfuse's ``monitors``, ``table_view_presets`` and
``default_llm_models``, which share the database. Only the two new tables belong
in this revision.

Revision ID: 0028
Revises: 0027
Create Date: 2026-08-21
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0028"
down_revision: str | None = "0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "curie"


def upgrade() -> None:
    op.create_table(
        "agent_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        # Nullable for the same reason approvals are: a run with no deployment
        # binding still acts on the world.
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("turn_id", sa.String(), nullable=False),
        sa.Column("tool", sa.String(), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        # What a restore replays. Its absence is what makes an action final.
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "snapshot_status", sa.String(), server_default="absent", nullable=False
        ),
        # What the action left. The world-moved check compares the live resource
        # against this, not against the snapshot, which is where it came FROM.
        sa.Column("post_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome", sa.String(), server_default="unknown", nullable=False),
        sa.Column("outcome_detail", sa.String(), nullable=True),
        sa.Column("irreversible_reason", sa.String(), nullable=True),
        sa.Column("undo_status", sa.String(), server_default="recorded", nullable=False),
        sa.Column("undone_at", sa.DateTime(), nullable=True),
        sa.Column("undone_by", sa.String(), nullable=True),
        sa.Column("reply_kind", sa.String(), nullable=True),
        sa.Column("reply_channel", sa.String(), nullable=True),
        sa.Column("card_channel", sa.String(), nullable=True),
        # Idempotency under at-least-once redelivery: a redelivered turn that
        # replays the same call adopts this row instead of forking one.
        sa.Column("dedupe_key", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["agent_id"], [f"{SCHEMA}.agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
        schema=SCHEMA,
    )
    for column in ("agent_id", "conversation_id", "turn_id", "outcome", "undo_status"):
        op.create_index(
            op.f(f"ix_{SCHEMA}_agent_actions_{column}"),
            "agent_actions",
            [column],
            unique=False,
            schema=SCHEMA,
        )

    op.create_table(
        "action_audit_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("actor_channel", sa.String(), nullable=True),
        # A refusal's diagnosis. The world-moved case puts the expected and the
        # observed state in ``evidence``.
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["action_id"], [f"{SCHEMA}.agent_actions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_index(
        op.f(f"ix_{SCHEMA}_action_audit_entries_action_id"),
        "action_audit_entries",
        ["action_id"],
        unique=False,
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Audit entries first: they carry the foreign key.
    op.drop_index(
        op.f(f"ix_{SCHEMA}_action_audit_entries_action_id"),
        table_name="action_audit_entries",
        schema=SCHEMA,
    )
    op.drop_table("action_audit_entries", schema=SCHEMA)
    for column in ("undo_status", "outcome", "turn_id", "conversation_id", "agent_id"):
        op.drop_index(
            op.f(f"ix_{SCHEMA}_agent_actions_{column}"),
            table_name="agent_actions",
            schema=SCHEMA,
        )
    op.drop_table("agent_actions", schema=SCHEMA)
